docs-build: use Python 3.13 image (#924)
docs builds are breaking here like this:

```text
WARNING: Failed to import rapidsmpf.integrations.ray.
Possible hints:
* AttributeError: module 'rapidsmpf.integrations' has no attribute 'ray'
* ModuleNotFoundError: No module named 'ray'
```

([build link](https://github.com/rapidsai/rapidsmpf/actions/runs/23301819724/job/67766153628#step:13:2122))

I think that's because `rapidsai/ci-conda:{rapids-version}-latest` now points to Python 3.14 images (https://github.com/rapidsai/ci-imgs/pull/383) and there aren't `ray` conda packages for Python 3.14 yet (#897).

This fixes that by pinning to a specific Python 3.13 image.

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Tom Augspurger (https://github.com/TomAugspurger)
  - Gil Forsyth (https://github.com/gforsyth)

URL: https://github.com/rapidsai/rapidsmpf/pull/924