Add <cstring> header for std::memcpy (#335)
Devcontainer builds are failing: https://github.com/rapidsai/devcontainers/actions/runs/15420568024/job/43475266470?pr=522#step:9:9487

```
/home/coder/rapidsmpf/cpp/src/shuffler/chunk.cpp:113:10: error: 'memcpy' is not a member of 'std'; did you mean 'wmemcpy'?
113 |     std::memcpy(&chunk_id, msg.data() + offset, sizeof(ChunkID));
    |          ^~~~~~
    |          wmemcpy
```

The header `<cstring>` that defines `std::memcpy` needs to be included in this file.

Authors:
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - Mads R. B. Kristensen (https://github.com/madsbk)

URL: https://github.com/rapidsai/rapidsmpf/pull/335