Adding `-Wno-ignored-optimization-argument` (#1091)
Recent gcc upgrade in conda seems to have added `-fno-merge-constants` to `CXXFLAGS`, and this conflicts with clang-tidy. 
```bash
[ 36%] Building CXX object _deps/gtest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
error: optimization flag '-fno-merge-constants' is not supported [clang-diagnostic-ignored-optimization-argument]
4570 warnings and 1 error generated.
Error while processing /home/nperera/git/rapidsmpf/cpp/src/bootstrap/bootstrap.cpp.
Suppressed 4570 warnings (4570 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
```

This PR adds  `-Wno-ignored-optimization-argument` to counter the clang-tidy error.

Authors:
  - Niranda Perera (https://github.com/nirandaperera)

Approvers:
  - Mads R. B. Kristensen (https://github.com/madsbk)

URL: https://github.com/rapidsai/rapidsmpf/pull/1091