Move Buffer::overloaded dispatch helper to top level (#238)
GCC versions prior to v12.0 had a bug in class template argument deduction rules: they were incorrectly required to live at namespace scope.

For example, the following definition

    struct Foo {
      template <typename... Ts> struct overloaded : Ts... {
        using Ts::operator()...;
      };
      template <typename... Ts>
      overloaded(Ts...) -> overloaded<Ts...>;
    };

Produces the compile error

    error: deduction guide 'Foo::overloaded(Ts ...) -> Foo::overloaded<Ts ...>' must be declared at namespace scope
        6 |   overloaded(Ts...) -> overloaded<Ts...>;
          |   ^~~~~~~~~~

In contrast, both clang, and later versions of GCC, correctly accept this definition. See
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79501 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100983 for details.

Since we still advertise support for GCC 11, and pip-based devcontainer builds use GCC 11, work around this bug by moving the overloaded dispatch helper (used in methods that visit the variant storage) to a top-level anonymous namespace.

Authors:
  - Lawrence Mitchell (https://github.com/wence-)

Approvers:
  - Niranda Perera (https://github.com/nirandaperera)

URL: https://github.com/rapidsai/rapidsmpf/pull/238